//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHunterApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationID { get; set; }
        public string Id { get; set; }
        public Nullable<int> ListingID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Listing Listing { get; set; }
    }
}
